apiVersion: v1
kind: Pod
metadata:
  name: curl-pod
  namespace: apps-dev
  labels:
    name: curl
spec:
  containers:
  - name: curl
    image: radial/busyboxplus:curl
    command:
      - "sh"
      - "-c"
      - >
        while true; do
          sleep 1;
        done