apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    tool: curl 
  name: curl-pod-lab
  namespace: apps-dev
spec:
  imagePullSecrets:
  - name: myregistry-secret
  containers:
  - name: curlpod
    image: radial/busyboxplus:curl
    command:
    - sh
    - -c
    - while true; do sleep 1; done
    resources:
      requests:
        memory: "64Mi"
        cpu: "125m"
      limits:
        memory: "64Mi"
        cpu: "125m"